class aaConfig:
    loginModalFieldClass1    = "sidenav-toggle"
    loginModalFieldClass2    = "iconcolorsignup"
    loginEmailFieldId        = "sso-login-email-input"
    loginPasswordFieldId     = "sso-login-password-input"
    loginButtonFieldClass    = "sso-button"
    loginButtonFieldType     = "submit"
    loginPrompt1             = "userName"
    loginPrompt2             = "ng-star-inserted"
    departureButtonField     = "home-origin-autocomplete-heatmap"
    departureBoxField        = "home-origin-autocomplete-heatmapstation-combobox"
    departureListField       = "home-origin-autocomplete-heatmaplist-"
    arrivalBoxField          = "home-destination-autocomplete-heatmapstation-combobox"
    arrivalListField         = "home-destination-autocomplete-heatmaplist-"
